/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * MCP Protocol Endpoint (Server-Sent Events)
         * @description GET endpoint for Server-Sent Events (SSE) streaming. Used for server-to-client messages in MCP protocol.
         */
        get: operations["mcp_protocol_sse"];
        put?: never;
        /**
         * MCP Protocol Endpoint (JSON-RPC)
         * @description Main endpoint for MCP protocol communication. Supports JSON-RPC 2.0 requests for tools, resources, and prompts.
         */
        post: operations["mcp_protocol"];
        /**
         * Terminate MCP Session
         * @description Explicitly terminate an MCP session
         */
        delete: operations["mcp_protocol_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/get_available_pokemon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Available Pokémon (GET)
         * @description Get available Pokémon in the draft pool with optional filters. Supports query parameters for simple filtering.
         */
        get: operations["get_available_pokemon_get"];
        put?: never;
        /**
         * Get Available Pokémon
         * @description Get available Pokémon in the draft pool with optional filters
         */
        post: operations["get_available_pokemon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/get_draft_status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Draft Status
         * @description Get current draft session status including current pick, round, and whose turn it is
         */
        post: operations["get_draft_status"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/get_team_budget": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Team Budget
         * @description Get team's draft budget including total, spent, and remaining points
         */
        post: operations["get_team_budget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/get_team_picks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Team Picks
         * @description Get all draft picks for a team
         */
        post: operations["get_team_picks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/get_pokemon_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Pokémon Types
         * @description Get Pokémon type information (primary and secondary types) from pokepedia_pokemon table
         */
        post: operations["get_pokemon_types"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/get_smogon_meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Smogon Meta
         * @description Get competitive meta data from Smogon for a Pokémon
         */
        post: operations["get_smogon_meta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/get_ability_mechanics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Ability Mechanics
         * @description Get detailed mechanics explanation for a Pokémon ability
         */
        post: operations["get_ability_mechanics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/get_move_mechanics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Move Mechanics
         * @description Get detailed mechanics explanation for a Pokémon move
         */
        post: operations["get_move_mechanics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze_pick_value": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Pick Value
         * @description Analyze if a Pokémon pick is good value based on point cost and competitive viability
         */
        post: operations["analyze_pick_value"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OAuth Token Endpoint
         * @description OAuth 2.0 token endpoint supporting client_credentials grant type. Returns JWT access tokens for MCP server authentication.
         */
        post: operations["oauth_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/oauth-authorization-server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OAuth Authorization Server Discovery
         * @description OAuth 2.0 Authorization Server Metadata (RFC 8414). Returns OAuth server configuration including endpoints and supported features.
         */
        get: operations["oauth_discovery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/mcp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * MCP Discovery Endpoint
         * @description MCP server discovery endpoint. Returns server capabilities, version, and endpoint information.
         */
        get: operations["mcp_discovery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Returns server health status, version, and session statistics
         */
        get: operations["health_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/functions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAI Function Calling Format
         * @description Returns all tools in OpenAI function calling format for SDK integration
         */
        get: operations["openai_functions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OpenAPI Specification
         * @description Returns this OpenAPI specification in JSON format
         */
        get: operations["openapi_spec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @enum {string} */
                code: "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "VALIDATION_ERROR" | "RATE_LIMIT_EXCEEDED" | "DATABASE_ERROR" | "INTERNAL_SERVER_ERROR" | "SERVICE_UNAVAILABLE" | "TOOL_EXECUTION_FAILED";
                message: string;
                /** @description Additional error details */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        JsonRpcError: {
            /** @enum {string} */
            jsonrpc: "2.0";
            error: {
                /**
                 * @description JSON-RPC error code
                 * @example -32000
                 */
                code: number;
                message: string;
                /** @description Additional error data */
                data?: {
                    [key: string]: unknown;
                };
            };
            id: string | number;
        };
        ValidationError: {
            error: {
                /** @enum {string} */
                code: "VALIDATION_ERROR";
                /** @example Request validation failed */
                message: string;
                details: {
                    fields?: {
                        path?: string;
                        message?: string;
                    }[];
                };
            };
        };
    };
    responses: {
        /** @description Bad Request - Invalid parameters or validation error */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"] | components["schemas"]["ValidationError"];
            };
        };
        /** @description Unauthorized - Invalid or missing API key or OAuth token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "Invalid or missing authentication credentials"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate Limit Exceeded - Too many requests */
        RateLimitExceeded: {
            headers: {
                /** @description Maximum requests allowed in window */
                "RateLimit-Limit"?: number;
                /** @description Remaining requests in current window */
                "RateLimit-Remaining"?: number;
                /** @description Unix timestamp when rate limit resets */
                "RateLimit-Reset"?: number;
                /** @description Seconds to wait before retrying */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "RATE_LIMIT_EXCEEDED",
                 *         "message": "Too many requests. Please try again later.",
                 *         "details": {
                 *           "retry_after": 900
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal Server Error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "INTERNAL_SERVER_ERROR",
                 *         "message": "An internal server error occurred"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    mcp_protocol_sse: {
        parameters: {
            query?: never;
            header?: {
                /** @description Session ID for stateful MCP communication */
                "MCP-Session-Id"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    mcp_protocol: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description JSON-RPC version (must be "2.0")
                     * @enum {string}
                     */
                    jsonrpc: "2.0";
                    /**
                     * @description MCP method name
                     * @example tools/call
                     * @enum {string}
                     */
                    method: "initialize" | "tools/list" | "tools/call" | "resources/list" | "resources/read" | "prompts/list" | "prompts/get";
                    /** @description Method-specific parameters */
                    params?: {
                        [key: string]: unknown;
                    };
                    /** @description Request ID for matching responses */
                    id: string | number;
                };
            };
        };
        responses: {
            /** @description Successful JSON-RPC response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        jsonrpc: "2.0";
                        /** @description Method-specific result */
                        result?: {
                            [key: string]: unknown;
                        };
                        error?: components["schemas"]["JsonRpcError"];
                        id: (string | number) | null;
                    };
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Session not found or invalid */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonRpcError"];
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            500: components["responses"]["InternalServerError"];
            /** @description Server at capacity (max sessions reached) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonRpcError"];
                };
            };
        };
    };
    mcp_protocol_delete: {
        parameters: {
            query?: never;
            header: {
                /** @description Session ID to terminate */
                "MCP-Session-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session terminated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Session terminated */
                        status?: string;
                    };
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    get_available_pokemon_get: {
        parameters: {
            query?: {
                /** @description Maximum number of results */
                limit?: number;
                /**
                 * @description Point value range as "[min,max]" or "min,max"
                 * @example [1,20]
                 */
                point_range?: string;
                /** @description Pokémon generation number */
                generation?: number;
                /** @description Pokémon type filter */
                type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pokemon: {
                            pokemon_name: string;
                            point_value: number;
                            generation?: number;
                            available: boolean;
                        }[];
                        count: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
            500: components["responses"]["InternalServerError"];
        };
    };
    get_available_pokemon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    point_range?: number[];
                    generation?: number;
                    type?: string;
                    /** @default 100 */
                    limit?: number;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pokemon: {
                            pokemon_name: string;
                            point_value: number;
                            generation?: number;
                            available: boolean;
                        }[];
                        count: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            500: components["responses"]["InternalServerError"];
        };
    };
    get_draft_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    season_id?: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        session_id: string;
                        status: string;
                        current_pick: number;
                        current_round: number;
                        current_team_id?: string;
                        total_picks: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            500: components["responses"]["InternalServerError"];
        };
    };
    get_team_budget: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    team_id: string;
                    season_id?: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        team_id: string;
                        total_points: number;
                        spent_points: number;
                        remaining_points: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            500: components["responses"]["InternalServerError"];
        };
    };
    get_team_picks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    team_id: string;
                    season_id?: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        team_id: string;
                        picks: {
                            pokemon_name: string;
                            point_value: number;
                            pick_number: number;
                            round: number;
                        }[];
                        total_picks: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            500: components["responses"]["InternalServerError"];
        };
    };
    get_pokemon_types: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pokemon_name: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pokemon_name: string;
                        type_primary?: string;
                        type_secondary?: string;
                        types: string[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            500: components["responses"]["InternalServerError"];
        };
    };
    get_smogon_meta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pokemon_name: string;
                    /** @default gen9ou */
                    format?: string;
                    source_date?: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pokemon_name: string;
                        format: string;
                        generation?: number;
                        tier?: string;
                        usage_rate?: number;
                        roles: string[];
                        common_moves: string[];
                        common_items: string[];
                        common_abilities: string[];
                        common_evs?: unknown;
                        checks: string[];
                        counters: string[];
                        source_date?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            500: components["responses"]["InternalServerError"];
        };
    };
    get_ability_mechanics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ability_name: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ability_name: string;
                        description: string;
                        mechanics: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            500: components["responses"]["InternalServerError"];
        };
    };
    get_move_mechanics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    move_name: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        move_name: string;
                        description: string;
                        mechanics: string;
                        power?: number;
                        accuracy?: number;
                        pp?: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            500: components["responses"]["InternalServerError"];
        };
    };
    analyze_pick_value: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    pokemon_name: string;
                    point_value: number;
                    /** @default gen9ou */
                    format?: string;
                };
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pokemon_name: string;
                        point_value: number;
                        analysis: string;
                        value_score: number;
                        recommendation: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            500: components["responses"]["InternalServerError"];
        };
    };
    oauth_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /**
                     * @description OAuth grant type (only client_credentials supported)
                     * @enum {string}
                     */
                    grant_type: "client_credentials";
                    /** @description OAuth client ID (if not using Basic Auth) */
                    client_id?: string;
                    /** @description OAuth client secret (if not using Basic Auth) */
                    client_secret?: string;
                    /**
                     * @description OAuth scope (default: "mcp")
                     * @default mcp
                     */
                    scope?: string;
                };
                "application/json": {
                    /** @enum {string} */
                    grant_type: "client_credentials";
                    client_id?: string;
                    client_secret?: string;
                    /** @default mcp */
                    scope?: string;
                };
            };
        };
        responses: {
            /** @description Token issued successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description JWT access token */
                        access_token: string;
                        /**
                         * @example Bearer
                         * @enum {string}
                         */
                        token_type: "Bearer";
                        /**
                         * @description Token expiration time in seconds
                         * @example 3600
                         */
                        expires_in: number;
                        /** @example mcp */
                        scope?: string;
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        error?: "invalid_request" | "unsupported_grant_type";
                        error_description?: string;
                    };
                };
            };
            /** @description Invalid client credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        error?: "invalid_client";
                        error_description?: string;
                    };
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            500: components["responses"]["InternalServerError"];
        };
    };
    oauth_discovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OAuth server metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example https://mcp-draft-pool.moodmnky.com */
                        issuer?: string;
                        /** @example https://mcp-draft-pool.moodmnky.com/token */
                        token_endpoint?: string;
                        /** @example https://mcp-draft-pool.moodmnky.com/register */
                        registration_endpoint?: string;
                        /**
                         * @example [
                         *       "client_credentials"
                         *     ]
                         */
                        grant_types_supported?: string[];
                        /**
                         * @example [
                         *       "client_secret_basic",
                         *       "client_secret_post"
                         *     ]
                         */
                        token_endpoint_auth_methods_supported?: string[];
                    };
                };
            };
            500: components["responses"]["InternalServerError"];
        };
    };
    mcp_discovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MCP server metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 2024-11-05 */
                        mcpVersion?: string;
                        /** @example poke-mnky-draft-pool */
                        serverName?: string;
                        /** @example 1.0.1 */
                        serverVersion?: string;
                        /** @example 2024-11-05 */
                        protocolVersion?: string;
                        capabilities?: {
                            tools?: Record<string, never>;
                            prompts?: Record<string, never>;
                            resources?: Record<string, never>;
                        };
                        endpoints?: {
                            /** @example https://mcp-draft-pool.moodmnky.com/mcp */
                            mcp?: string;
                        };
                    };
                };
            };
        };
    };
    health_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        /** @example poke-mnky-draft-pool-mcp-server */
                        service?: string;
                        /** @example 1.0.1 */
                        version?: string;
                        tools?: {
                            /** @example 9 */
                            count?: number;
                            available?: string[];
                        };
                        sessions?: {
                            active?: number;
                            max?: number;
                            utilization?: number;
                            oldestSessionAge?: number;
                        };
                        cache?: {
                            hits?: number;
                            misses?: number;
                            size?: number;
                        };
                    };
                };
            };
        };
    };
    openai_functions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAI function definitions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        tools?: {
                            /** @enum {string} */
                            type?: "function";
                            function?: {
                                name?: string;
                                description?: string;
                                parameters?: Record<string, never>;
                            };
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    openapi_spec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI 3.0 specification */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
}
