-- Migration: Populate sheets_draft_pool for Production
-- Generated from seed.sql
-- Purpose: Seed sheets_draft_pool table in production (seed.sql is local-only)
-- 
-- This migration contains the same INSERT statements as seed.sql
-- but runs in production when migration is applied.
-- 
-- Idempotent: Uses ON CONFLICT DO UPDATE to handle re-runs safely
-- Total Pokemon: 778
-- Generated: 2026-01-19T11:17:02.000Z
--
-- Note: pokemon_id may be NULL if Pokemon doesn't exist in pokemon_cache yet
-- This is safe - pokemon_id can be populated later when pokemon_cache is updated
--
-- Strategy: Insert all rows with pokemon_id = NULL initially to avoid FK violations
-- pokemon_id can be populated later when pokemon_cache is updated
-- This is safe since pokemon_id is nullable and can be updated via ON CONFLICT

INSERT INTO sheets_draft_pool (pokemon_name, point_value, is_available, generation, sheet_name, sheet_row, sheet_column, pokemon_id)
VALUES
  ('Flutter Mane', 20, true, NULL, 'Draft Board', 5, 'J', NULL),
  ('Gouging Fire', 20, true, NULL, 'Draft Board', 6, 'J', NULL),
  ('Mewtwo', 20, true, NULL, 'Draft Board', 7, 'J', NULL),
  ('Raging Bolt', 20, true, NULL, 'Draft Board', 8, 'J', NULL),
  ('Roaring Moon', 20, true, NULL, 'Draft Board', 9, 'J', NULL),
  ('Urshifu Rapid Strike', 20, true, NULL, 'Draft Board', 10, 'J', NULL),
  ('Urshifu Single Strike', 20, true, NULL, 'Draft Board', 11, 'J', NULL),
  ('Archaludon', 19, true, NULL, 'Draft Board', 5, 'M', NULL),
  ('Chi-Yu', 19, true, NULL, 'Draft Board', 6, 'M', NULL),
  ('Chien-Pao', 19, true, NULL, 'Draft Board', 7, 'M', NULL),
  ('Deoxys Attack', 19, true, NULL, 'Draft Board', 8, 'M', NULL),
  ('Dragapult', 19, true, NULL, 'Draft Board', 9, 'M', NULL),
  ('Great Tusk', 19, true, NULL, 'Draft Board', 10, 'M', NULL),
  ('Iron Bundle', 19, true, NULL, 'Draft Board', 11, 'M', NULL),
  ('Iron Valiant', 19, true, NULL, 'Draft Board', 12, 'M', NULL),
  ('Palafin', 19, true, NULL, 'Draft Board', 13, 'M', NULL),
  ('Pecharunt', 19, true, NULL, 'Draft Board', 14, 'M', NULL),
  ('Ursaluna Bloodmoon', 19, true, NULL, 'Draft Board', 15, 'M', NULL),
  ('Deoxys', 18, true, NULL, 'Draft Board', 5, 'P', NULL),
  ('Deoxys Defense', 18, true, NULL, 'Draft Board', 6, 'P', NULL),
  ('Enamorus Incarnate', 18, true, NULL, 'Draft Board', 7, 'P', NULL),
  ('Garchomp', 18, true, NULL, 'Draft Board', 8, 'P', NULL),
  ('Iron Treads', 18, true, NULL, 'Draft Board', 9, 'P', NULL),
  ('Kommo-o', 18, true, NULL, 'Draft Board', 10, 'P', NULL),
  ('Landorus Therian', 18, true, NULL, 'Draft Board', 11, 'P', NULL),
  ('Ting-Lu', 18, true, NULL, 'Draft Board', 12, 'P', NULL),
  ('Walking Wake', 18, true, NULL, 'Draft Board', 13, 'P', NULL),
  ('Wo-Chien', 18, true, NULL, 'Draft Board', 14, 'P', NULL),
  ('Annihilape', 17, true, NULL, 'Draft Board', 5, 'S', NULL),
  ('Basculegion Female', 17, true, NULL, 'Draft Board', 6, 'S', NULL),
  ('Basculegion Male', 17, true, NULL, 'Draft Board', 7, 'S', NULL),
  ('Cinderace', 17, true, NULL, 'Draft Board', 8, 'S', NULL),
  ('Darkrai', 17, true, NULL, 'Draft Board', 9, 'S', NULL),
  ('Dragonite', 17, true, NULL, 'Draft Board', 10, 'S', NULL),
  ('Garganacl', 17, true, NULL, 'Draft Board', 11, 'S', NULL),
  ('Gholdengo', 17, true, NULL, 'Draft Board', 12, 'S', NULL),
  ('Ho-Oh', 17, true, NULL, 'Draft Board', 13, 'S', NULL),
  ('Infernape', 17, true, NULL, 'Draft Board', 14, 'S', NULL),
  ('Kingambit', 17, true, NULL, 'Draft Board', 15, 'S', NULL),
  ('Meowscarada', 17, true, NULL, 'Draft Board', 16, 'S', NULL),
  ('Ogerpon Cornerstone', 17, true, NULL, 'Draft Board', 17, 'S', NULL),
  ('Ogerpon Hearthflame', 17, true, NULL, 'Draft Board', 18, 'S', NULL),
  ('Ogerpon Wellspring', 17, true, NULL, 'Draft Board', 19, 'S', NULL),
  ('Rotom Wash', 17, true, NULL, 'Draft Board', 20, 'S', NULL),
  ('Sneasler', 17, true, NULL, 'Draft Board', 21, 'S', NULL),
  ('Baxcalibur', 16, true, NULL, 'Draft Board', 5, 'V', NULL),
  ('Deoxys Speed', 16, true, NULL, 'Draft Board', 6, 'V', NULL),
  ('Heatran', 16, true, NULL, 'Draft Board', 7, 'V', NULL),
  ('Hoopa Unbound', 16, true, NULL, 'Draft Board', 8, 'V', NULL),
  ('Hydreigon', 16, true, NULL, 'Draft Board', 9, 'V', NULL),
  ('Iron Boulder', 16, true, NULL, 'Draft Board', 10, 'V', NULL),
  ('Keldeo', 16, true, NULL, 'Draft Board', 11, 'V', NULL),
  ('Kyurem', 16, true, NULL, 'Draft Board', 12, 'V', NULL),
  ('Mamoswine', 16, true, NULL, 'Draft Board', 13, 'V', NULL),
  ('Mew', 16, true, NULL, 'Draft Board', 14, 'V', NULL),
  ('Ogerpon', 16, true, NULL, 'Draft Board', 15, 'V', NULL),
  ('Salamence', 16, true, NULL, 'Draft Board', 16, 'V', NULL),
  ('Samurott Hisuian', 16, true, NULL, 'Draft Board', 17, 'V', NULL),
  ('Slowking Galarian', 16, true, NULL, 'Draft Board', 18, 'V', NULL),
  ('Tornadus Therian', 16, true, NULL, 'Draft Board', 19, 'V', NULL),
  ('Tyranitar', 16, true, NULL, 'Draft Board', 20, 'V', NULL),
  ('Ursaluna', 16, true, NULL, 'Draft Board', 21, 'V', NULL),
  ('Volcanion', 16, true, NULL, 'Draft Board', 22, 'V', NULL),
  ('Weavile', 16, true, NULL, 'Draft Board', 23, 'V', NULL),
  ('Articuno Galarian', 15, true, NULL, 'Draft Board', 5, 'Y', NULL),
  ('Azumarill', 15, true, NULL, 'Draft Board', 6, 'Y', NULL),
  ('Clefable', 15, true, NULL, 'Draft Board', 7, 'Y', NULL),
  ('Entei', 15, true, NULL, 'Draft Board', 8, 'Y', NULL),
  ('Gliscor', 15, true, NULL, 'Draft Board', 9, 'Y', NULL),
  ('Greninja', 15, true, NULL, 'Draft Board', 10, 'Y', NULL),
  ('Haxorus', 15, true, NULL, 'Draft Board', 11, 'Y', NULL),
  ('Iron Crown', 15, true, NULL, 'Draft Board', 12, 'Y', NULL),
  ('Iron Moth', 15, true, NULL, 'Draft Board', 13, 'Y', NULL),
  ('Jirachi', 15, true, NULL, 'Draft Board', 14, 'Y', NULL),
  ('Latias', 15, true, NULL, 'Draft Board', 15, 'Y', NULL),
  ('Latios', 15, true, NULL, 'Draft Board', 16, 'Y', NULL),
  ('Lilligant Hisuian', 15, true, NULL, 'Draft Board', 17, 'Y', NULL),
  ('Lycanroc Dusk', 15, true, NULL, 'Draft Board', 18, 'Y', NULL),
  ('Mandibuzz', 15, true, NULL, 'Draft Board', 19, 'Y', NULL),
  ('Meloetta', 15, true, NULL, 'Draft Board', 20, 'Y', NULL),
  ('Metagross', 15, true, NULL, 'Draft Board', 21, 'Y', NULL),
  ('Munkidori', 15, true, NULL, 'Draft Board', 22, 'Y', NULL),
  ('Necrozma', 15, true, NULL, 'Draft Board', 23, 'Y', NULL),
  ('Quaquaval', 15, true, NULL, 'Draft Board', 24, 'Y', NULL),
  ('Raikou', 15, true, NULL, 'Draft Board', 25, 'Y', NULL),
  ('Regice', 15, true, NULL, 'Draft Board', 26, 'Y', NULL),
  ('Regirock', 15, true, NULL, 'Draft Board', 27, 'Y', NULL),
  ('Registeel', 15, true, NULL, 'Draft Board', 28, 'Y', NULL),
  ('Skeledirge', 15, true, NULL, 'Draft Board', 29, 'Y', NULL),
  ('Slowking', 15, true, NULL, 'Draft Board', 30, 'Y', NULL),
  ('Suicune', 15, true, NULL, 'Draft Board', 31, 'Y', NULL),
  ('Terapagos', 15, true, NULL, 'Draft Board', 32, 'Y', NULL),
  ('Thundurus Incarnate', 15, true, NULL, 'Draft Board', 33, 'Y', NULL),
  ('Thundurus Therian', 15, true, NULL, 'Draft Board', 34, 'Y', NULL),
  ('Volcarona', 15, true, NULL, 'Draft Board', 35, 'Y', NULL),
  ('Zapdos', 15, true, NULL, 'Draft Board', 36, 'Y', NULL),
  ('Zapdos Galarian', 15, true, NULL, 'Draft Board', 37, 'Y', NULL),
  ('Zarude', 15, true, NULL, 'Draft Board', 38, 'Y', NULL),
  ('Corviknight', 14, true, NULL, 'Draft Board', 5, '\', NULL),
  ('Diancie', 14, true, NULL, 'Draft Board', 6, '\', NULL),
  ('Iron Hands', 14, true, NULL, 'Draft Board', 7, '\', NULL),
  ('Krookodile', 14, true, NULL, 'Draft Board', 8, '\', NULL),
  ('Lucario', 14, true, NULL, 'Draft Board', 9, '\', NULL),
  ('Lugia', 14, true, NULL, 'Draft Board', 10, '\', NULL),
  ('Manaphy', 14, true, NULL, 'Draft Board', 11, '\', NULL),
  ('Moltres', 14, true, NULL, 'Draft Board', 12, '\', NULL),
  ('Ninetales Alolan', 14, true, NULL, 'Draft Board', 13, '\', NULL),
  ('Okidogi', 14, true, NULL, 'Draft Board', 14, '\', NULL),
  ('Regidrago', 14, true, NULL, 'Draft Board', 15, '\', NULL),
  ('Regieleki', 14, true, NULL, 'Draft Board', 16, '\', NULL),
  ('Rotom Heat', 14, true, NULL, 'Draft Board', 17, '\', NULL),
  ('Scizor', 14, true, NULL, 'Draft Board', 18, '\', NULL),
  ('Slowbro', 14, true, NULL, 'Draft Board', 19, '\', NULL),
  ('Terrakion', 14, true, NULL, 'Draft Board', 20, '\', NULL),
  ('Toxapex', 14, true, NULL, 'Draft Board', 21, '\', NULL),
  ('Amoonguss', 13, true, NULL, 'Draft Board', 5, '_', NULL),
  ('Arcanine Hisuian', 13, true, NULL, 'Draft Board', 6, '_', NULL),
  ('Azelf', 13, true, NULL, 'Draft Board', 7, '_', NULL),
  ('Ceruledge', 13, true, NULL, 'Draft Board', 8, '_', NULL),
  ('Cloyster', 13, true, NULL, 'Draft Board', 9, '_', NULL),
  ('Crawdaunt', 13, true, NULL, 'Draft Board', 10, '_', NULL),
  ('Exeggutor Alolan', 13, true, NULL, 'Draft Board', 11, '_', NULL),
  ('Glastrier', 13, true, NULL, 'Draft Board', 12, '_', NULL),
  ('Gothitelle', 13, true, NULL, 'Draft Board', 13, '_', NULL),
  ('Hawlucha', 13, true, NULL, 'Draft Board', 14, '_', NULL),
  ('Iron Jugulis', 13, true, NULL, 'Draft Board', 15, '_', NULL),
  ('Iron Leaves', 13, true, NULL, 'Draft Board', 16, '_', NULL),
  ('Kleavor', 13, true, NULL, 'Draft Board', 17, '_', NULL),
  ('Lokix', 13, true, NULL, 'Draft Board', 18, '_', NULL),
  ('Mienshao', 13, true, NULL, 'Draft Board', 19, '_', NULL),
  ('Moltres Galarian', 13, true, NULL, 'Draft Board', 20, '_', NULL),
  ('Porygon2', 13, true, NULL, 'Draft Board', 21, '_', NULL),
  ('Regigigas', 13, true, NULL, 'Draft Board', 22, '_', NULL),
  ('Rillaboom', 13, true, NULL, 'Draft Board', 23, '_', NULL),
  ('Scream Tail', 13, true, NULL, 'Draft Board', 24, '_', NULL),
  ('Slither Wing', 13, true, NULL, 'Draft Board', 25, '_', NULL),
  ('Tornadus Incarnate', 13, true, NULL, 'Draft Board', 26, '_', NULL),
  ('Arcanine', 12, true, NULL, 'Draft Board', 5, 'b', NULL),
  ('Armarouge', 12, true, NULL, 'Draft Board', 6, 'b', NULL),
  ('Articuno', 12, true, NULL, 'Draft Board', 7, 'b', NULL),
  ('Breloom', 12, true, NULL, 'Draft Board', 8, 'b', NULL),
  ('Calyrex', 12, true, NULL, 'Draft Board', 9, 'b', NULL),
  ('Clodsire', 12, true, NULL, 'Draft Board', 10, 'b', NULL),
  ('Cobalion', 12, true, NULL, 'Draft Board', 11, 'b', NULL),
  ('Conkeldurr', 12, true, NULL, 'Draft Board', 12, 'b', NULL),
  ('Cresselia', 12, true, NULL, 'Draft Board', 13, 'b', NULL),
  ('Enamorus Therian', 12, true, NULL, 'Draft Board', 14, 'b', NULL),
  ('Espathra', 12, true, NULL, 'Draft Board', 15, 'b', NULL),
  ('Fezandipiti', 12, true, NULL, 'Draft Board', 16, 'b', NULL),
  ('Flygon', 12, true, NULL, 'Draft Board', 17, 'b', NULL),
  ('Gengar', 12, true, NULL, 'Draft Board', 18, 'b', NULL),
  ('Glimmora', 12, true, NULL, 'Draft Board', 19, 'b', NULL),
  ('Grimmsnarl', 12, true, NULL, 'Draft Board', 20, 'b', NULL),
  ('Gyarados', 12, true, NULL, 'Draft Board', 21, 'b', NULL),
  ('Hippowdon', 12, true, NULL, 'Draft Board', 22, 'b', NULL),
  ('Mesprit', 12, true, NULL, 'Draft Board', 23, 'b', NULL),
  ('Overqwil', 12, true, NULL, 'Draft Board', 24, 'b', NULL),
  ('Phione', 12, true, NULL, 'Draft Board', 25, 'b', NULL),
  ('Porygon-Z', 12, true, NULL, 'Draft Board', 26, 'b', NULL),
  ('Ribombee', 12, true, NULL, 'Draft Board', 27, 'b', NULL),
  ('Sandy Shocks', 12, true, NULL, 'Draft Board', 28, 'b', NULL),
  ('Shaymin', 12, true, NULL, 'Draft Board', 29, 'b', NULL),
  ('Snorlax', 12, true, NULL, 'Draft Board', 30, 'b', NULL),
  ('Sylveon', 12, true, NULL, 'Draft Board', 31, 'b', NULL),
  ('Uxie', 12, true, NULL, 'Draft Board', 32, 'b', NULL),
  ('Virizion', 12, true, NULL, 'Draft Board', 33, 'b', NULL),
  ('Whimsicott', 12, true, NULL, 'Draft Board', 34, 'b', NULL),
  ('Zoroark Hisuian', 12, true, NULL, 'Draft Board', 35, 'b', NULL),
  ('Barraskewda', 11, true, NULL, 'Draft Board', 5, 'e', NULL),
  ('Blaziken', 11, true, NULL, 'Draft Board', 6, 'e', NULL),
  ('Brute Bonnet', 11, true, NULL, 'Draft Board', 7, 'e', NULL),
  ('Dondozo', 11, true, NULL, 'Draft Board', 8, 'e', NULL),
  ('Donphan', 11, true, NULL, 'Draft Board', 9, 'e', NULL),
  ('Dudunsparce', 11, true, NULL, 'Draft Board', 10, 'e', NULL),
  ('Duraludon', 11, true, NULL, 'Draft Board', 11, 'e', NULL),
  ('Empoleon', 11, true, NULL, 'Draft Board', 12, 'e', NULL),
  ('Florges', 11, true, NULL, 'Draft Board', 13, 'e', NULL),
  ('Gallade', 11, true, NULL, 'Draft Board', 14, 'e', NULL),
  ('Gardevoir', 11, true, NULL, 'Draft Board', 15, 'e', NULL),
  ('Goodra Hisuian', 11, true, NULL, 'Draft Board', 16, 'e', NULL),
  ('Hatterene', 11, true, NULL, 'Draft Board', 17, 'e', NULL),
  ('Hoopa', 11, true, NULL, 'Draft Board', 18, 'e', NULL),
  ('Hydrapple', 11, true, NULL, 'Draft Board', 19, 'e', NULL),
  ('Incineroar', 11, true, NULL, 'Draft Board', 20, 'e', NULL),
  ('Inteleon', 11, true, NULL, 'Draft Board', 21, 'e', NULL),
  ('Iron Thorns', 11, true, NULL, 'Draft Board', 22, 'e', NULL),
  ('Maushold', 11, true, NULL, 'Draft Board', 23, 'e', NULL),
  ('Meowstic Male', 11, true, NULL, 'Draft Board', 24, 'e', NULL),
  ('Milotic', 11, true, NULL, 'Draft Board', 25, 'e', NULL),
  ('Pawmot', 11, true, NULL, 'Draft Board', 26, 'e', NULL),
  ('Pelipper', 11, true, NULL, 'Draft Board', 27, 'e', NULL),
  ('Primarina', 11, true, NULL, 'Draft Board', 28, 'e', NULL),
  ('Rhydon', 11, true, NULL, 'Draft Board', 29, 'e', NULL),
  ('Sinistcha', 11, true, NULL, 'Draft Board', 30, 'e', NULL),
  ('Slowbro Galarian', 11, true, NULL, 'Draft Board', 31, 'e', NULL),
  ('Torkoal', 11, true, NULL, 'Draft Board', 32, 'e', NULL),
  ('Toucannon', 11, true, NULL, 'Draft Board', 33, 'e', NULL),
  ('Toxtricity Amped', 11, true, NULL, 'Draft Board', 34, 'e', NULL),
  ('Toxtricity Low Key', 11, true, NULL, 'Draft Board', 35, 'e', NULL),
  ('Venusaur', 11, true, NULL, 'Draft Board', 36, 'e', NULL),
  ('Weezing Galarian', 11, true, NULL, 'Draft Board', 37, 'e', NULL),
  ('Decidueye', 10, true, NULL, 'Draft Board', 5, 'h', NULL),
  ('Delphox', 10, true, NULL, 'Draft Board', 6, 'h', NULL),
  ('Dugtrio', 10, true, NULL, 'Draft Board', 7, 'h', NULL),
  ('Espeon', 10, true, NULL, 'Draft Board', 8, 'h', NULL),
  ('Gastrodon', 10, true, NULL, 'Draft Board', 9, 'h', NULL),
  ('Goodra', 10, true, NULL, 'Draft Board', 10, 'h', NULL),
  ('Heracross', 10, true, NULL, 'Draft Board', 11, 'h', NULL),
  ('Hitmonlee', 10, true, NULL, 'Draft Board', 12, 'h', NULL),
  ('Jolteon', 10, true, NULL, 'Draft Board', 13, 'h', NULL),
  ('Kilowattrel', 10, true, NULL, 'Draft Board', 14, 'h', NULL),
  ('Klefki', 10, true, NULL, 'Draft Board', 15, 'h', NULL),
  ('Magnezone', 10, true, NULL, 'Draft Board', 16, 'h', NULL),
  ('Mimikyu', 10, true, NULL, 'Draft Board', 17, 'h', NULL),
  ('Muk Alolan', 10, true, NULL, 'Draft Board', 18, 'h', NULL),
  ('Ninetales', 10, true, NULL, 'Draft Board', 19, 'h', NULL),
  ('Noivern', 10, true, NULL, 'Draft Board', 20, 'h', NULL),
  ('Politoed', 10, true, NULL, 'Draft Board', 21, 'h', NULL),
  ('Rotom Mow', 10, true, NULL, 'Draft Board', 22, 'h', NULL),
  ('Salazzle', 10, true, NULL, 'Draft Board', 23, 'h', NULL),
  ('Slaking', 10, true, NULL, 'Draft Board', 24, 'h', NULL),
  ('Staraptor', 10, true, NULL, 'Draft Board', 25, 'h', NULL),
  ('Talonflame', 10, true, NULL, 'Draft Board', 26, 'h', NULL),
  ('Vaporeon', 10, true, NULL, 'Draft Board', 27, 'h', NULL),
  ('Yanmega', 10, true, NULL, 'Draft Board', 28, 'h', NULL),
  ('Zoroark', 10, true, NULL, 'Draft Board', 29, 'h', NULL),
  ('Bisharp', 9, true, NULL, 'Draft Board', 5, 'k', NULL),
  ('Bronzong', 9, true, NULL, 'Draft Board', 6, 'k', NULL),
  ('Chandelure', 9, true, NULL, 'Draft Board', 7, 'k', NULL),
  ('Cyclizar', 9, true, NULL, 'Draft Board', 8, 'k', NULL),
  ('Dragalge', 9, true, NULL, 'Draft Board', 9, 'k', NULL),
  ('Drednaw', 9, true, NULL, 'Draft Board', 10, 'k', NULL),
  ('Dusclops', 9, true, NULL, 'Draft Board', 11, 'k', NULL),
  ('Flamigo', 9, true, NULL, 'Draft Board', 12, 'k', NULL),
  ('Flapple', 9, true, NULL, 'Draft Board', 13, 'k', NULL),
  ('Hitmontop', 9, true, NULL, 'Draft Board', 14, 'k', NULL),
  ('Honchkrow', 9, true, NULL, 'Draft Board', 15, 'k', NULL),
  ('Houndstone', 9, true, NULL, 'Draft Board', 16, 'k', NULL),
  ('Indeedee Female', 9, true, NULL, 'Draft Board', 17, 'k', NULL),
  ('Indeedee Male', 9, true, NULL, 'Draft Board', 18, 'k', NULL),
  ('Kingdra', 9, true, NULL, 'Draft Board', 19, 'k', NULL),
  ('Mismagius', 9, true, NULL, 'Draft Board', 20, 'k', NULL),
  ('Primeape', 9, true, NULL, 'Draft Board', 21, 'k', NULL),
  ('Revavroom', 9, true, NULL, 'Draft Board', 22, 'k', NULL),
  ('Rhyperior', 9, true, NULL, 'Draft Board', 23, 'k', NULL),
  ('Serperior', 9, true, NULL, 'Draft Board', 24, 'k', NULL),
  ('Skarmory', 9, true, NULL, 'Draft Board', 25, 'k', NULL),
  ('Swampert', 9, true, NULL, 'Draft Board', 26, 'k', NULL),
  ('Tinkaton', 9, true, NULL, 'Draft Board', 27, 'k', NULL),
  ('Torterra', 9, true, NULL, 'Draft Board', 28, 'k', NULL),
  ('Typhlosion Hisuian', 9, true, NULL, 'Draft Board', 29, 'k', NULL),
  ('Abomasnow', 8, true, NULL, 'Draft Board', 5, 'n', NULL),
  ('Alomomola', 8, true, NULL, 'Draft Board', 6, 'n', NULL),
  ('Ampharos', 8, true, NULL, 'Draft Board', 7, 'n', NULL),
  ('Bellibolt', 8, true, NULL, 'Draft Board', 8, 'n', NULL),
  ('Blissey', 8, true, NULL, 'Draft Board', 9, 'n', NULL),
  ('Braviary Hisuian', 8, true, NULL, 'Draft Board', 10, 'n', NULL),
  ('Cetitan', 8, true, NULL, 'Draft Board', 11, 'n', NULL),
  ('Charizard', 8, true, NULL, 'Draft Board', 12, 'n', NULL),
  ('Chesnaught', 8, true, NULL, 'Draft Board', 13, 'n', NULL),
  ('Comfey', 8, true, NULL, 'Draft Board', 14, 'n', NULL),
  ('Copperajah', 8, true, NULL, 'Draft Board', 15, 'n', NULL),
  ('Eelektross', 8, true, NULL, 'Draft Board', 16, 'n', NULL),
  ('Electivire', 8, true, NULL, 'Draft Board', 17, 'n', NULL),
  ('Electrode Hisuian', 8, true, NULL, 'Draft Board', 18, 'n', NULL),
  ('Emboar', 8, true, NULL, 'Draft Board', 19, 'n', NULL),
  ('Excadrill', 8, true, NULL, 'Draft Board', 20, 'n', NULL),
  ('Farigiraf', 8, true, NULL, 'Draft Board', 21, 'n', NULL),
  ('Gogoat', 8, true, NULL, 'Draft Board', 22, 'n', NULL),
  ('Granbull', 8, true, NULL, 'Draft Board', 23, 'n', NULL),
  ('Hariyama', 8, true, NULL, 'Draft Board', 24, 'n', NULL),
  ('Hitmonchan', 8, true, NULL, 'Draft Board', 25, 'n', NULL),
  ('Illumise', 8, true, NULL, 'Draft Board', 26, 'n', NULL),
  ('Lycanroc', 8, true, NULL, 'Draft Board', 27, 'n', NULL),
  ('Magmortar', 8, true, NULL, 'Draft Board', 28, 'n', NULL),
  ('Murkrow', 8, true, NULL, 'Draft Board', 29, 'n', NULL),
  ('Orthworm', 8, true, NULL, 'Draft Board', 30, 'n', NULL),
  ('Piloswine', 8, true, NULL, 'Draft Board', 31, 'n', NULL),
  ('Polteageist', 8, true, NULL, 'Draft Board', 32, 'n', NULL),
  ('Reuniclus', 8, true, NULL, 'Draft Board', 33, 'n', NULL),
  ('Sableye', 8, true, NULL, 'Draft Board', 34, 'n', NULL),
  ('Tauros', 8, true, NULL, 'Draft Board', 35, 'n', NULL),
  ('Tauros Paldean Aqua', 8, true, NULL, 'Draft Board', 36, 'n', NULL),
  ('Tauros Paldean Blaze', 8, true, NULL, 'Draft Board', 37, 'n', NULL),
  ('Toedscruel', 8, true, NULL, 'Draft Board', 38, 'n', NULL),
  ('Tsareena', 8, true, NULL, 'Draft Board', 39, 'n', NULL),
  ('Umbreon', 8, true, NULL, 'Draft Board', 40, 'n', NULL),
  ('Venomoth', 8, true, NULL, 'Draft Board', 41, 'n', NULL),
  ('Vikavolt', 8, true, NULL, 'Draft Board', 42, 'n', NULL),
  ('Vivillon', 8, true, NULL, 'Draft Board', 43, 'n', NULL),
  ('Volbeat', 8, true, NULL, 'Draft Board', 44, 'n', NULL),
  ('Wyrdeer', 8, true, NULL, 'Draft Board', 45, 'n', NULL),
  ('Altaria', 7, true, NULL, 'Draft Board', 5, 'q', NULL),
  ('Arboliva', 7, true, NULL, 'Draft Board', 6, 'q', NULL),
  ('Bastiodon', 7, true, NULL, 'Draft Board', 7, 'q', NULL),
  ('Brambleghast', 7, true, NULL, 'Draft Board', 8, 'q', NULL),
  ('Chansey', 7, true, NULL, 'Draft Board', 9, 'q', NULL),
  ('Clawitzer', 7, true, NULL, 'Draft Board', 10, 'q', NULL),
  ('Ditto', 7, true, NULL, 'Draft Board', 11, 'q', NULL),
  ('Flareon', 7, true, NULL, 'Draft Board', 12, 'q', NULL),
  ('Floatzel', 7, true, NULL, 'Draft Board', 13, 'q', NULL),
  ('Forretress', 7, true, NULL, 'Draft Board', 14, 'q', NULL),
  ('Galvantula', 7, true, NULL, 'Draft Board', 15, 'q', NULL),
  ('Gligar', 7, true, NULL, 'Draft Board', 16, 'q', NULL),
  ('Lanturn', 7, true, NULL, 'Draft Board', 17, 'q', NULL),
  ('Lapras', 7, true, NULL, 'Draft Board', 18, 'q', NULL),
  ('Medicham', 7, true, NULL, 'Draft Board', 19, 'q', NULL),
  ('Minior', 7, true, NULL, 'Draft Board', 20, 'q', NULL),
  ('Passimian', 7, true, NULL, 'Draft Board', 21, 'q', NULL),
  ('Perrserker', 7, true, NULL, 'Draft Board', 22, 'q', NULL),
  ('Poliwrath', 7, true, NULL, 'Draft Board', 23, 'q', NULL),
  ('Probopass', 7, true, NULL, 'Draft Board', 24, 'q', NULL),
  ('Qwilfish Hisuian', 7, true, NULL, 'Draft Board', 25, 'q', NULL),
  ('Raichu Alolan', 7, true, NULL, 'Draft Board', 26, 'q', NULL),
  ('Rampardos', 7, true, NULL, 'Draft Board', 27, 'q', NULL),
  ('Rotom Fan', 7, true, NULL, 'Draft Board', 28, 'q', NULL),
  ('Rotom Frost', 7, true, NULL, 'Draft Board', 29, 'q', NULL),
  ('Sandslash Alolan', 7, true, NULL, 'Draft Board', 30, 'q', NULL),
  ('Sceptile', 7, true, NULL, 'Draft Board', 31, 'q', NULL),
  ('Scovillain', 7, true, NULL, 'Draft Board', 32, 'q', NULL),
  ('Scrafty', 7, true, NULL, 'Draft Board', 33, 'q', NULL),
  ('Tentacruel', 7, true, NULL, 'Draft Board', 34, 'q', NULL),
  ('Toxicroak', 7, true, NULL, 'Draft Board', 35, 'q', NULL),
  ('Ursaring', 7, true, NULL, 'Draft Board', 36, 'q', NULL),
  ('Vigoroth', 7, true, NULL, 'Draft Board', 37, 'q', NULL),
  ('Weezing', 7, true, NULL, 'Draft Board', 38, 'q', NULL),
  ('Wigglytuff', 7, true, NULL, 'Draft Board', 39, 'q', NULL),
  ('Araquanid', 6, true, NULL, 'Draft Board', 5, 't', NULL),
  ('Ariados', 6, true, NULL, 'Draft Board', 6, 't', NULL),
  ('Beartic', 6, true, NULL, 'Draft Board', 7, 't', NULL),
  ('Bombirdier', 6, true, NULL, 'Draft Board', 8, 't', NULL),
  ('Braviary', 6, true, NULL, 'Draft Board', 9, 't', NULL),
  ('Camerupt', 6, true, NULL, 'Draft Board', 10, 't', NULL),
  ('Coalossal', 6, true, NULL, 'Draft Board', 11, 't', NULL),
  ('Decidueye Hisuian', 6, true, NULL, 'Draft Board', 12, 't', NULL),
  ('Drifblim', 6, true, NULL, 'Draft Board', 13, 't', NULL),
  ('Dugtrio Alolan', 6, true, NULL, 'Draft Board', 14, 't', NULL),
  ('Eiscue', 6, true, NULL, 'Draft Board', 15, 't', NULL),
  ('Electrode', 6, true, NULL, 'Draft Board', 16, 't', NULL),
  ('Feraligatr', 6, true, NULL, 'Draft Board', 17, 't', NULL),
  ('Froslass', 6, true, NULL, 'Draft Board', 18, 't', NULL),
  ('Frosmoth', 6, true, NULL, 'Draft Board', 19, 't', NULL),
  ('Glalie', 6, true, NULL, 'Draft Board', 20, 't', NULL),
  ('Golem Alolan', 6, true, NULL, 'Draft Board', 21, 't', NULL),
  ('Grafaiai', 6, true, NULL, 'Draft Board', 22, 't', NULL),
  ('Houndoom', 6, true, NULL, 'Draft Board', 23, 't', NULL),
  ('Hypno', 6, true, NULL, 'Draft Board', 24, 't', NULL),
  ('Jumpluff', 6, true, NULL, 'Draft Board', 25, 't', NULL),
  ('Kricketune', 6, true, NULL, 'Draft Board', 26, 't', NULL),
  ('Leafeon', 6, true, NULL, 'Draft Board', 27, 't', NULL),
  ('Lilligant', 6, true, NULL, 'Draft Board', 28, 't', NULL),
  ('Ludicolo', 6, true, NULL, 'Draft Board', 29, 't', NULL),
  ('Luxray', 6, true, NULL, 'Draft Board', 30, 't', NULL),
  ('Lycanroc Midnight', 6, true, NULL, 'Draft Board', 31, 't', NULL),
  ('Magneton', 6, true, NULL, 'Draft Board', 32, 't', NULL),
  ('Malamar', 6, true, NULL, 'Draft Board', 33, 't', NULL),
  ('Meganium', 6, true, NULL, 'Draft Board', 34, 't', NULL),
  ('Morpeko', 6, true, NULL, 'Draft Board', 35, 't', NULL),
  ('Mudsdale', 6, true, NULL, 'Draft Board', 36, 't', NULL),
  ('Naclstack', 6, true, NULL, 'Draft Board', 37, 't', NULL),
  ('Oricorio', 6, true, NULL, 'Draft Board', 38, 't', NULL),
  ('Palossand', 6, true, NULL, 'Draft Board', 39, 't', NULL),
  ('Persian Alolan', 6, true, NULL, 'Draft Board', 40, 't', NULL),
  ('Pincurchin', 6, true, NULL, 'Draft Board', 41, 't', NULL),
  ('Pyroar', 6, true, NULL, 'Draft Board', 42, 't', NULL),
  ('Qwilfish', 6, true, NULL, 'Draft Board', 43, 't', NULL),
  ('Raichu', 6, true, NULL, 'Draft Board', 44, 't', NULL),
  ('Rotom', 6, true, NULL, 'Draft Board', 45, 't', NULL),
  ('Samurott', 6, true, NULL, 'Draft Board', 46, 't', NULL),
  ('Sandaconda', 6, true, NULL, 'Draft Board', 47, 't', NULL),
  ('Scyther', 6, true, NULL, 'Draft Board', 48, 't', NULL),
  ('Shiftry', 6, true, NULL, 'Draft Board', 49, 't', NULL),
  ('Sneasel', 6, true, NULL, 'Draft Board', 50, 't', NULL),
  ('Spidops', 6, true, NULL, 'Draft Board', 51, 't', NULL),
  ('Tauros Paldean', 6, true, NULL, 'Draft Board', 52, 't', NULL),
  ('Trumbeak', 6, true, NULL, 'Draft Board', 53, 't', NULL),
  ('Typhlosion', 6, true, NULL, 'Draft Board', 54, 't', NULL),
  ('Veluza', 6, true, NULL, 'Draft Board', 55, 't', NULL),
  ('Vespiquen', 6, true, NULL, 'Draft Board', 56, 't', NULL),
  ('Vileplume', 6, true, NULL, 'Draft Board', 57, 't', NULL),
  ('Whiscash', 6, true, NULL, 'Draft Board', 58, 't', NULL),
  ('Wugtrio', 6, true, NULL, 'Draft Board', 59, 't', NULL),
  ('Zebstrika', 6, true, NULL, 'Draft Board', 60, 't', NULL),
  ('Alcremie', 5, true, NULL, 'Draft Board', 5, 'w', NULL),
  ('Ambipom', 5, true, NULL, 'Draft Board', 6, 'w', NULL),
  ('Appletun', 5, true, NULL, 'Draft Board', 7, 'w', NULL),
  ('Avalugg', 5, true, NULL, 'Draft Board', 8, 'w', NULL),
  ('Avalugg Hisuian', 5, true, NULL, 'Draft Board', 9, 'w', NULL),
  ('Banette', 5, true, NULL, 'Draft Board', 10, 'w', NULL),
  ('Bellossom', 5, true, NULL, 'Draft Board', 11, 'w', NULL),
  ('Blastoise', 5, true, NULL, 'Draft Board', 12, 'w', NULL),
  ('Bramblin', 5, true, NULL, 'Draft Board', 13, 'w', NULL),
  ('Cacturne', 5, true, NULL, 'Draft Board', 14, 'w', NULL),
  ('Cinccino', 5, true, NULL, 'Draft Board', 15, 'w', NULL),
  ('Crabominable', 5, true, NULL, 'Draft Board', 16, 'w', NULL),
  ('Dachsbun', 5, true, NULL, 'Draft Board', 17, 'w', NULL),
  ('Dedenne', 5, true, NULL, 'Draft Board', 18, 'w', NULL),
  ('Dewgong', 5, true, NULL, 'Draft Board', 19, 'w', NULL),
  ('Dodrio', 5, true, NULL, 'Draft Board', 20, 'w', NULL),
  ('Dragonair', 5, true, NULL, 'Draft Board', 21, 'w', NULL),
  ('Electabuzz', 5, true, NULL, 'Draft Board', 22, 'w', NULL),
  ('Exeggutor', 5, true, NULL, 'Draft Board', 23, 'w', NULL),
  ('Glaceon', 5, true, NULL, 'Draft Board', 24, 'w', NULL),
  ('Golem', 5, true, NULL, 'Draft Board', 25, 'w', NULL),
  ('Golurk', 5, true, NULL, 'Draft Board', 26, 'w', NULL),
  ('Gothorita', 5, true, NULL, 'Draft Board', 27, 'w', NULL),
  ('Greedent', 5, true, NULL, 'Draft Board', 28, 'w', NULL),
  ('Grumpig', 5, true, NULL, 'Draft Board', 29, 'w', NULL),
  ('Gumshoos', 5, true, NULL, 'Draft Board', 30, 'w', NULL),
  ('Gurdurr', 5, true, NULL, 'Draft Board', 31, 'w', NULL),
  ('Hakamo-o', 5, true, NULL, 'Draft Board', 32, 'w', NULL),
  ('Lurantis', 5, true, NULL, 'Draft Board', 33, 'w', NULL),
  ('Magcargo', 5, true, NULL, 'Draft Board', 34, 'w', NULL),
  ('Magmar', 5, true, NULL, 'Draft Board', 35, 'w', NULL),
  ('Masquerain', 5, true, NULL, 'Draft Board', 36, 'w', NULL),
  ('Metang', 5, true, NULL, 'Draft Board', 37, 'w', NULL),
  ('Muk', 5, true, NULL, 'Draft Board', 38, 'w', NULL),
  ('Oinkologne', 5, true, NULL, 'Draft Board', 39, 'w', NULL),
  ('Oranguru', 5, true, NULL, 'Draft Board', 40, 'w', NULL),
  ('Persian', 5, true, NULL, 'Draft Board', 41, 'w', NULL),
  ('Porygon', 5, true, NULL, 'Draft Board', 42, 'w', NULL),
  ('Quagsire', 5, true, NULL, 'Draft Board', 43, 'w', NULL),
  ('Rabsca', 5, true, NULL, 'Draft Board', 44, 'w', NULL),
  ('Sawsbuck', 5, true, NULL, 'Draft Board', 45, 'w', NULL),
  ('Seadra', 5, true, NULL, 'Draft Board', 46, 'w', NULL),
  ('Seviper', 5, true, NULL, 'Draft Board', 47, 'w', NULL),
  ('Shelgon', 5, true, NULL, 'Draft Board', 48, 'w', NULL),
  ('Skuntank', 5, true, NULL, 'Draft Board', 49, 'w', NULL),
  ('Smeargle', 5, true, NULL, 'Draft Board', 50, 'w', NULL),
  ('Sneasel Hisuian', 5, true, NULL, 'Draft Board', 51, 'w', NULL),
  ('Spiritomb', 5, true, NULL, 'Draft Board', 52, 'w', NULL),
  ('Swalot', 5, true, NULL, 'Draft Board', 53, 'w', NULL),
  ('Swanna', 5, true, NULL, 'Draft Board', 54, 'w', NULL),
  ('Trevenant', 5, true, NULL, 'Draft Board', 55, 'w', NULL),
  ('Vibrava', 5, true, NULL, 'Draft Board', 56, 'w', NULL),
  ('Victreebel', 5, true, NULL, 'Draft Board', 57, 'w', NULL),
  ('Zangoose', 5, true, NULL, 'Draft Board', 58, 'w', NULL),
  ('Zweilous', 5, true, NULL, 'Draft Board', 59, 'w', NULL),
  ('Bruxish', 4, true, NULL, 'Draft Board', 5, 'z', NULL),
  ('Clefairy', 4, true, NULL, 'Draft Board', 6, 'z', NULL),
  ('Combusken', 4, true, NULL, 'Draft Board', 7, 'z', NULL),
  ('Cottonee', 4, true, NULL, 'Draft Board', 8, 'z', NULL),
  ('Cramorant', 4, true, NULL, 'Draft Board', 9, 'z', NULL),
  ('Cryogonal', 4, true, NULL, 'Draft Board', 10, 'z', NULL),
  ('Drakloak', 4, true, NULL, 'Draft Board', 11, 'z', NULL),
  ('Dunsparce', 4, true, NULL, 'Draft Board', 12, 'z', NULL),
  ('Dusknoir', 4, true, NULL, 'Draft Board', 13, 'z', NULL),
  ('Falinks', 4, true, NULL, 'Draft Board', 14, 'z', NULL),
  ('Floragato', 4, true, NULL, 'Draft Board', 15, 'z', NULL),
  ('Fraxure', 4, true, NULL, 'Draft Board', 16, 'z', NULL),
  ('Frogadier', 4, true, NULL, 'Draft Board', 17, 'z', NULL),
  ('Gabite', 4, true, NULL, 'Draft Board', 18, 'z', NULL),
  ('Girafarig', 4, true, NULL, 'Draft Board', 19, 'z', NULL),
  ('Golduck', 4, true, NULL, 'Draft Board', 20, 'z', NULL),
  ('Haunter', 4, true, NULL, 'Draft Board', 21, 'z', NULL),
  ('Klawf', 4, true, NULL, 'Draft Board', 22, 'z', NULL),
  ('Komala', 4, true, NULL, 'Draft Board', 23, 'z', NULL),
  ('Leavanny', 4, true, NULL, 'Draft Board', 24, 'z', NULL),
  ('Lumineon', 4, true, NULL, 'Draft Board', 25, 'z', NULL),
  ('Mabosstiff', 4, true, NULL, 'Draft Board', 26, 'z', NULL),
  ('Mightyena', 4, true, NULL, 'Draft Board', 27, 'z', NULL),
  ('Misdreavus', 4, true, NULL, 'Draft Board', 28, 'z', NULL),
  ('Morgrem', 4, true, NULL, 'Draft Board', 29, 'z', NULL),
  ('Noctowl', 4, true, NULL, 'Draft Board', 30, 'z', NULL),
  ('Oinkologne Female', 4, true, NULL, 'Draft Board', 31, 'z', NULL),
  ('Pachirisu', 4, true, NULL, 'Draft Board', 32, 'z', NULL),
  ('Pawmo', 4, true, NULL, 'Draft Board', 33, 'z', NULL),
  ('Pikachu', 4, true, NULL, 'Draft Board', 34, 'z', NULL),
  ('Pupitar', 4, true, NULL, 'Draft Board', 35, 'z', NULL),
  ('Quaxwell', 4, true, NULL, 'Draft Board', 36, 'z', NULL),
  ('Sandslash', 4, true, NULL, 'Draft Board', 37, 'z', NULL),
  ('Skiploom', 4, true, NULL, 'Draft Board', 38, 'z', NULL),
  ('Sliggoo Hisuian', 4, true, NULL, 'Draft Board', 39, 'z', NULL),
  ('Squawkabilly', 4, true, NULL, 'Draft Board', 40, 'z', NULL),
  ('Stonjourner', 4, true, NULL, 'Draft Board', 41, 'z', NULL),
  ('Sudowoodo', 4, true, NULL, 'Draft Board', 42, 'z', NULL),
  ('Sunflora', 4, true, NULL, 'Draft Board', 43, 'z', NULL),
  ('Tatsugiri', 4, true, NULL, 'Draft Board', 44, 'z', NULL),
  ('Thwackey', 4, true, NULL, 'Draft Board', 45, 'z', NULL),
  ('Toedscool', 4, true, NULL, 'Draft Board', 46, 'z', NULL),
  ('Tropius', 4, true, NULL, 'Draft Board', 47, 'z', NULL),
  ('Arctibax', 3, true, NULL, 'Draft Board', 5, '}', NULL),
  ('Bayleef', 3, true, NULL, 'Draft Board', 6, '}', NULL),
  ('Braixen', 3, true, NULL, 'Draft Board', 7, '}', NULL),
  ('Brionne', 3, true, NULL, 'Draft Board', 8, '}', NULL),
  ('Charmeleon', 3, true, NULL, 'Draft Board', 9, '}', NULL),
  ('Corvisquire', 3, true, NULL, 'Draft Board', 10, '}', NULL),
  ('Crocalor', 3, true, NULL, 'Draft Board', 11, '}', NULL),
  ('Croconaw', 3, true, NULL, 'Draft Board', 12, '}', NULL),
  ('Dartrix', 3, true, NULL, 'Draft Board', 13, '}', NULL),
  ('Dewott', 3, true, NULL, 'Draft Board', 14, '}', NULL),
  ('Dipplin', 3, true, NULL, 'Draft Board', 15, '}', NULL),
  ('Dolliv', 3, true, NULL, 'Draft Board', 16, '}', NULL),
  ('Drizzile', 3, true, NULL, 'Draft Board', 17, '}', NULL),
  ('Duosion', 3, true, NULL, 'Draft Board', 18, '}', NULL),
  ('Eelektrik', 3, true, NULL, 'Draft Board', 19, '}', NULL),
  ('Flaaffy', 3, true, NULL, 'Draft Board', 20, '}', NULL),
  ('Fletchinder', 3, true, NULL, 'Draft Board', 21, '}', NULL),
  ('Gloom', 3, true, NULL, 'Draft Board', 22, '}', NULL),
  ('Graveler', 3, true, NULL, 'Draft Board', 23, '}', NULL),
  ('Grotle', 3, true, NULL, 'Draft Board', 24, '}', NULL),
  ('Grovyle', 3, true, NULL, 'Draft Board', 25, '}', NULL),
  ('Hattrem', 3, true, NULL, 'Draft Board', 26, '}', NULL),
  ('Ivysaur', 3, true, NULL, 'Draft Board', 27, '}', NULL),
  ('Kirlia', 3, true, NULL, 'Draft Board', 28, '}', NULL),
  ('Krokorok', 3, true, NULL, 'Draft Board', 29, '}', NULL),
  ('Lampent', 3, true, NULL, 'Draft Board', 30, '}', NULL),
  ('Lombre', 3, true, NULL, 'Draft Board', 31, '}', NULL),
  ('Luxio', 3, true, NULL, 'Draft Board', 32, '}', NULL),
  ('Marill', 3, true, NULL, 'Draft Board', 33, '}', NULL),
  ('Marshtomp', 3, true, NULL, 'Draft Board', 34, '}', NULL),
  ('Meowstic Female', 3, true, NULL, 'Draft Board', 35, '}', NULL),
  ('Monferno', 3, true, NULL, 'Draft Board', 36, '}', NULL),
  ('Nuzleaf', 3, true, NULL, 'Draft Board', 37, '}', NULL),
  ('Pignite', 3, true, NULL, 'Draft Board', 38, '}', NULL),
  ('Poliwhirl', 3, true, NULL, 'Draft Board', 39, '}', NULL),
  ('Prinplup', 3, true, NULL, 'Draft Board', 40, '}', NULL),
  ('Quilava', 3, true, NULL, 'Draft Board', 41, '}', NULL),
  ('Quilladin', 3, true, NULL, 'Draft Board', 42, '}', NULL),
  ('Raboot', 3, true, NULL, 'Draft Board', 43, '}', NULL),
  ('Rhyhorn', 3, true, NULL, 'Draft Board', 44, '}', NULL),
  ('Servine', 3, true, NULL, 'Draft Board', 45, '}', NULL),
  ('Sliggoo', 3, true, NULL, 'Draft Board', 46, '}', NULL),
  ('Snubbull', 3, true, NULL, 'Draft Board', 47, '}', NULL),
  ('Staravia', 3, true, NULL, 'Draft Board', 48, '}', NULL),
  ('Swadloon', 3, true, NULL, 'Draft Board', 49, '}', NULL),
  ('Tinkatuff', 3, true, NULL, 'Draft Board', 50, '}', NULL),
  ('Torracat', 3, true, NULL, 'Draft Board', 51, '}', NULL),
  ('Vullaby', 3, true, NULL, 'Draft Board', 52, '}', NULL),
  ('Wartortle', 3, true, NULL, 'Draft Board', 53, '}', NULL),
  ('Weepinbell', 3, true, NULL, 'Draft Board', 54, '}', NULL),
  ('Aipom', 2, true, NULL, 'Draft Board', 5, '', NULL),
  ('Arbok', 2, true, NULL, 'Draft Board', 6, '', NULL),
  ('Basculin Blue Stripe', 2, true, NULL, 'Draft Board', 7, '', NULL),
  ('Basculin Red Stripe', 2, true, NULL, 'Draft Board', 8, '', NULL),
  ('Carbink', 2, true, NULL, 'Draft Board', 9, '', NULL),
  ('Cetoddle', 2, true, NULL, 'Draft Board', 10, '', NULL),
  ('Delibird', 2, true, NULL, 'Draft Board', 11, '', NULL),
  ('Eevee', 2, true, NULL, 'Draft Board', 12, '', NULL),
  ('Furret', 2, true, NULL, 'Draft Board', 13, '', NULL),
  ('Glimmet', 2, true, NULL, 'Draft Board', 14, '', NULL),
  ('Graveler Alolan', 2, true, NULL, 'Draft Board', 15, '', NULL),
  ('Impidimp', 2, true, NULL, 'Draft Board', 16, '', NULL),
  ('Mareanie', 2, true, NULL, 'Draft Board', 17, '', NULL),
  ('Minun', 2, true, NULL, 'Draft Board', 18, '', NULL),
  ('Munchlax', 2, true, NULL, 'Draft Board', 19, '', NULL),
  ('Plusle', 2, true, NULL, 'Draft Board', 20, '', NULL),
  ('Riolu', 2, true, NULL, 'Draft Board', 21, '', NULL),
  ('Shroodle', 2, true, NULL, 'Draft Board', 22, '', NULL),
  ('Stantler', 2, true, NULL, 'Draft Board', 23, '', NULL),
  ('Steenee', 2, true, NULL, 'Draft Board', 24, '', NULL),
  ('Voltorb Hisuian', 2, true, NULL, 'Draft Board', 25, '', NULL),
  ('Yanma', 2, true, NULL, 'Draft Board', 26, '', NULL),
  ('Applin', 1, true, NULL, 'Draft Board', 5, '', NULL),
  ('Arrokuda', 1, true, NULL, 'Draft Board', 6, '', NULL),
  ('Axew', 1, true, NULL, 'Draft Board', 7, '', NULL),
  ('Azurill', 1, true, NULL, 'Draft Board', 8, '', NULL),
  ('Bagon', 1, true, NULL, 'Draft Board', 9, '', NULL),
  ('Barboach', 1, true, NULL, 'Draft Board', 10, '', NULL),
  ('Beldum', 1, true, NULL, 'Draft Board', 11, '', NULL),
  ('Bellsprout', 1, true, NULL, 'Draft Board', 12, '', NULL),
  ('Bergmite', 1, true, NULL, 'Draft Board', 13, '', NULL),
  ('Blitzle', 1, true, NULL, 'Draft Board', 14, '', NULL),
  ('Bonsly', 1, true, NULL, 'Draft Board', 15, '', NULL),
  ('Bounsweet', 1, true, NULL, 'Draft Board', 16, '', NULL),
  ('Bronzor', 1, true, NULL, 'Draft Board', 17, '', NULL),
  ('Buizel', 1, true, NULL, 'Draft Board', 18, '', NULL),
  ('Bulbasaur', 1, true, NULL, 'Draft Board', 19, '', NULL),
  ('Cacnea', 1, true, NULL, 'Draft Board', 20, '', NULL),
  ('Capsakid', 1, true, NULL, 'Draft Board', 21, '', NULL),
  ('Carkol', 1, true, NULL, 'Draft Board', 22, '', NULL),
  ('Charcadet', 1, true, NULL, 'Draft Board', 23, '', NULL),
  ('Charjabug', 1, true, NULL, 'Draft Board', 24, '', NULL),
  ('Charmander', 1, true, NULL, 'Draft Board', 25, '', NULL),
  ('Chespin', 1, true, NULL, 'Draft Board', 26, '', NULL),
  ('Chewtle', 1, true, NULL, 'Draft Board', 27, '', NULL),
  ('Chikorita', 1, true, NULL, 'Draft Board', 28, '', NULL),
  ('Chimchar', 1, true, NULL, 'Draft Board', 29, '', NULL),
  ('Chimecho', 1, true, NULL, 'Draft Board', 30, '', NULL),
  ('Chinchou', 1, true, NULL, 'Draft Board', 31, '', NULL),
  ('Chingling', 1, true, NULL, 'Draft Board', 32, '', NULL),
  ('Clauncher', 1, true, NULL, 'Draft Board', 33, '', NULL),
  ('Cleffa', 1, true, NULL, 'Draft Board', 34, '', NULL),
  ('Combee', 1, true, NULL, 'Draft Board', 35, '', NULL),
  ('Corphish', 1, true, NULL, 'Draft Board', 36, '', NULL),
  ('Crabrawler', 1, true, NULL, 'Draft Board', 37, '', NULL),
  ('Croagunk', 1, true, NULL, 'Draft Board', 38, '', NULL),
  ('Cubchoo', 1, true, NULL, 'Draft Board', 39, '', NULL),
  ('Cufant', 1, true, NULL, 'Draft Board', 40, '', NULL),
  ('Cutiefly', 1, true, NULL, 'Draft Board', 41, '', NULL),
  ('Cyndaquil', 1, true, NULL, 'Draft Board', 42, '', NULL),
  ('Deerling', 1, true, NULL, 'Draft Board', 43, '', NULL),
  ('Deino', 1, true, NULL, 'Draft Board', 44, '', NULL),
  ('Dewpider', 1, true, NULL, 'Draft Board', 45, '', NULL),
  ('Diglett', 1, true, NULL, 'Draft Board', 46, '', NULL),
  ('Diglett Alolan', 1, true, NULL, 'Draft Board', 47, '', NULL),
  ('Doduo', 1, true, NULL, 'Draft Board', 48, '', NULL),
  ('Dratini', 1, true, NULL, 'Draft Board', 49, '', NULL),
  ('Dreepy', 1, true, NULL, 'Draft Board', 50, '', NULL),
  ('Drifloon', 1, true, NULL, 'Draft Board', 51, '', NULL),
  ('Drilbur', 1, true, NULL, 'Draft Board', 52, '', NULL),
  ('Drowzee', 1, true, NULL, 'Draft Board', 53, '', NULL),
  ('Ducklett', 1, true, NULL, 'Draft Board', 54, '', NULL),
  ('Duskull', 1, true, NULL, 'Draft Board', 55, '', NULL),
  ('Ekans', 1, true, NULL, 'Draft Board', 56, '', NULL),
  ('Elekid', 1, true, NULL, 'Draft Board', 57, '', NULL),
  ('Exeggcute', 1, true, NULL, 'Draft Board', 58, '', NULL),
  ('Feebas', 1, true, NULL, 'Draft Board', 59, '', NULL),
  ('Fennekin', 1, true, NULL, 'Draft Board', 60, '', NULL),
  ('Fidough', 1, true, NULL, 'Draft Board', 61, '', NULL),
  ('Finizen', 1, true, NULL, 'Draft Board', 62, '', NULL),
  ('Finneon', 1, true, NULL, 'Draft Board', 63, '', NULL),
  ('Flabébé', 1, true, NULL, 'Draft Board', 64, '', NULL),
  ('Fletchling', 1, true, NULL, 'Draft Board', 65, '', NULL),
  ('Flittle', 1, true, NULL, 'Draft Board', 66, '', NULL),
  ('Floette', 1, true, NULL, 'Draft Board', 67, '', NULL),
  ('Fomantis', 1, true, NULL, 'Draft Board', 68, '', NULL),
  ('Foongus', 1, true, NULL, 'Draft Board', 69, '', NULL),
  ('Frigibax', 1, true, NULL, 'Draft Board', 70, '', NULL),
  ('Froakie', 1, true, NULL, 'Draft Board', 71, '', NULL),
  ('Fuecoco', 1, true, NULL, 'Draft Board', 72, '', NULL),
  ('Gastly', 1, true, NULL, 'Draft Board', 73, '', NULL),
  ('Geodude', 1, true, NULL, 'Draft Board', 74, '', NULL),
  ('Geodude Alolan', 1, true, NULL, 'Draft Board', 75, '', NULL),
  ('Gible', 1, true, NULL, 'Draft Board', 76, '', NULL),
  ('Gimmighoul', 1, true, NULL, 'Draft Board', 77, '', NULL),
  ('Golett', 1, true, NULL, 'Draft Board', 78, '', NULL),
  ('Goomy', 1, true, NULL, 'Draft Board', 79, '', NULL),
  ('Gothita', 1, true, NULL, 'Draft Board', 80, '', NULL),
  ('Greavard', 1, true, NULL, 'Draft Board', 81, '', NULL),
  ('Grimer', 1, true, NULL, 'Draft Board', 82, '', NULL),
  ('Grimer Alolan', 1, true, NULL, 'Draft Board', 83, '', NULL),
  ('Grookey', 1, true, NULL, 'Draft Board', 84, '', NULL),
  ('Growlithe', 1, true, NULL, 'Draft Board', 85, '', NULL),
  ('Growlithe Hisuian', 1, true, NULL, 'Draft Board', 86, '', NULL),
  ('Grubbin', 1, true, NULL, 'Draft Board', 87, '', NULL),
  ('Gulpin', 1, true, NULL, 'Draft Board', 88, '', NULL),
  ('Happiny', 1, true, NULL, 'Draft Board', 89, '', NULL),
  ('Hatenna', 1, true, NULL, 'Draft Board', 90, '', NULL),
  ('Hippopotas', 1, true, NULL, 'Draft Board', 91, '', NULL),
  ('Hoothoot', 1, true, NULL, 'Draft Board', 92, '', NULL),
  ('Hoppip', 1, true, NULL, 'Draft Board', 93, '', NULL),
  ('Horsea', 1, true, NULL, 'Draft Board', 94, '', NULL),
  ('Houndour', 1, true, NULL, 'Draft Board', 95, '', NULL),
  ('Igglybuff', 1, true, NULL, 'Draft Board', 96, '', NULL),
  ('Inkay', 1, true, NULL, 'Draft Board', 97, '', NULL),
  ('Jangmo-o', 1, true, NULL, 'Draft Board', 98, '', NULL),
  ('Jigglypuff', 1, true, NULL, 'Draft Board', 99, '', NULL),
  ('Joltik', 1, true, NULL, 'Draft Board', 100, '', NULL),
  ('Koffing', 1, true, NULL, 'Draft Board', 101, '', NULL),
  ('Kricketot', 1, true, NULL, 'Draft Board', 102, '', NULL),
  ('Kubfu', 1, true, NULL, 'Draft Board', 103, '', NULL),
  ('Larvesta', 1, true, NULL, 'Draft Board', 104, '', NULL),
  ('Larvitar', 1, true, NULL, 'Draft Board', 105, '', NULL),
  ('Lechonk', 1, true, NULL, 'Draft Board', 106, '', NULL),
  ('Litleo', 1, true, NULL, 'Draft Board', 107, '', NULL),
  ('Litten', 1, true, NULL, 'Draft Board', 108, '', NULL),
  ('Litwick', 1, true, NULL, 'Draft Board', 109, '', NULL),
  ('Lotad', 1, true, NULL, 'Draft Board', 110, '', NULL),
  ('Luvdisc', 1, true, NULL, 'Draft Board', 111, '', NULL),
  ('Magby', 1, true, NULL, 'Draft Board', 112, '', NULL),
  ('Magikarp', 1, true, NULL, 'Draft Board', 113, '', NULL),
  ('Magnemite', 1, true, NULL, 'Draft Board', 114, '', NULL),
  ('Makuhita', 1, true, NULL, 'Draft Board', 115, '', NULL),
  ('Mankey', 1, true, NULL, 'Draft Board', 116, '', NULL),
  ('Mareep', 1, true, NULL, 'Draft Board', 117, '', NULL),
  ('Maschiff', 1, true, NULL, 'Draft Board', 118, '', NULL),
  ('Meditite', 1, true, NULL, 'Draft Board', 119, '', NULL),
  ('Meowth', 1, true, NULL, 'Draft Board', 120, '', NULL),
  ('Meowth Alolan', 1, true, NULL, 'Draft Board', 121, '', NULL),
  ('Meowth Galarian', 1, true, NULL, 'Draft Board', 122, '', NULL),
  ('Mienfoo', 1, true, NULL, 'Draft Board', 123, '', NULL),
  ('Minccino', 1, true, NULL, 'Draft Board', 124, '', NULL),
  ('Mudbray', 1, true, NULL, 'Draft Board', 125, '', NULL),
  ('Mudkip', 1, true, NULL, 'Draft Board', 126, '', NULL),
  ('Nacli', 1, true, NULL, 'Draft Board', 127, '', NULL),
  ('Noibat', 1, true, NULL, 'Draft Board', 128, '', NULL),
  ('Nosepass', 1, true, NULL, 'Draft Board', 129, '', NULL),
  ('Numel', 1, true, NULL, 'Draft Board', 130, '', NULL),
  ('Nymble', 1, true, NULL, 'Draft Board', 131, '', NULL),
  ('Oddish', 1, true, NULL, 'Draft Board', 132, '', NULL),
  ('Oshawott', 1, true, NULL, 'Draft Board', 133, '', NULL),
  ('Pawmi', 1, true, NULL, 'Draft Board', 134, '', NULL),
  ('Pawniard', 1, true, NULL, 'Draft Board', 135, '', NULL),
  ('Petilil', 1, true, NULL, 'Draft Board', 136, '', NULL),
  ('Phanpy', 1, true, NULL, 'Draft Board', 137, '', NULL),
  ('Phantump', 1, true, NULL, 'Draft Board', 138, '', NULL),
  ('Pichu', 1, true, NULL, 'Draft Board', 139, '', NULL),
  ('Pikipek', 1, true, NULL, 'Draft Board', 140, '', NULL),
  ('Pineco', 1, true, NULL, 'Draft Board', 141, '', NULL),
  ('Piplup', 1, true, NULL, 'Draft Board', 142, '', NULL),
  ('Poliwag', 1, true, NULL, 'Draft Board', 143, '', NULL),
  ('Poltchageist', 1, true, NULL, 'Draft Board', 144, '', NULL),
  ('Poochyena', 1, true, NULL, 'Draft Board', 145, '', NULL),
  ('Popplio', 1, true, NULL, 'Draft Board', 146, '', NULL),
  ('Psyduck', 1, true, NULL, 'Draft Board', 147, '', NULL),
  ('Quaxly', 1, true, NULL, 'Draft Board', 148, '', NULL),
  ('Ralts', 1, true, NULL, 'Draft Board', 149, '', NULL),
  ('Rellor', 1, true, NULL, 'Draft Board', 150, '', NULL),
  ('Rockruff', 1, true, NULL, 'Draft Board', 151, '', NULL),
  ('Rolycoly', 1, true, NULL, 'Draft Board', 152, '', NULL),
  ('Rookidee', 1, true, NULL, 'Draft Board', 153, '', NULL),
  ('Rowlet', 1, true, NULL, 'Draft Board', 154, '', NULL),
  ('Rufflet', 1, true, NULL, 'Draft Board', 155, '', NULL),
  ('Salandit', 1, true, NULL, 'Draft Board', 156, '', NULL),
  ('Sandile', 1, true, NULL, 'Draft Board', 157, '', NULL),
  ('Sandshrew', 1, true, NULL, 'Draft Board', 158, '', NULL),
  ('Sandshrew Alolan', 1, true, NULL, 'Draft Board', 159, '', NULL),
  ('Sandygast', 1, true, NULL, 'Draft Board', 160, '', NULL),
  ('Scatterbug', 1, true, NULL, 'Draft Board', 161, '', NULL),
  ('Scorbunny', 1, true, NULL, 'Draft Board', 162, '', NULL),
  ('Scraggy', 1, true, NULL, 'Draft Board', 163, '', NULL),
  ('Seedot', 1, true, NULL, 'Draft Board', 164, '', NULL),
  ('Seel', 1, true, NULL, 'Draft Board', 165, '', NULL),
  ('Sentret', 1, true, NULL, 'Draft Board', 166, '', NULL),
  ('Sewaddle', 1, true, NULL, 'Draft Board', 167, '', NULL),
  ('Shellder', 1, true, NULL, 'Draft Board', 168, '', NULL),
  ('Shellos', 1, true, NULL, 'Draft Board', 169, '', NULL),
  ('Shieldon', 1, true, NULL, 'Draft Board', 170, '', NULL),
  ('Shinx', 1, true, NULL, 'Draft Board', 171, '', NULL),
  ('Shroomish', 1, true, NULL, 'Draft Board', 172, '', NULL),
  ('Shuppet', 1, true, NULL, 'Draft Board', 173, '', NULL),
  ('Silicobra', 1, true, NULL, 'Draft Board', 174, '', NULL),
  ('Sinistea', 1, true, NULL, 'Draft Board', 175, '', NULL),
  ('Skiddo', 1, true, NULL, 'Draft Board', 176, '', NULL),
  ('Skrelp', 1, true, NULL, 'Draft Board', 177, '', NULL),
  ('Skwovet', 1, true, NULL, 'Draft Board', 178, '', NULL),
  ('Slakoth', 1, true, NULL, 'Draft Board', 179, '', NULL),
  ('Slowpoke', 1, true, NULL, 'Draft Board', 180, '', NULL),
  ('Slowpoke Galarian', 1, true, NULL, 'Draft Board', 181, '', NULL),
  ('Slugma', 1, true, NULL, 'Draft Board', 182, '', NULL),
  ('Smoliv', 1, true, NULL, 'Draft Board', 183, '', NULL),
  ('Snivy', 1, true, NULL, 'Draft Board', 184, '', NULL),
  ('Snom', 1, true, NULL, 'Draft Board', 185, '', NULL),
  ('Snorunt', 1, true, NULL, 'Draft Board', 186, '', NULL),
  ('Snover', 1, true, NULL, 'Draft Board', 187, '', NULL),
  ('Sobble', 1, true, NULL, 'Draft Board', 188, '', NULL),
  ('Solosis', 1, true, NULL, 'Draft Board', 189, '', NULL),
  ('Spewpa', 1, true, NULL, 'Draft Board', 190, '', NULL),
  ('Spinarak', 1, true, NULL, 'Draft Board', 191, '', NULL),
  ('Spoink', 1, true, NULL, 'Draft Board', 192, '', NULL),
  ('Sprigatito', 1, true, NULL, 'Draft Board', 193, '', NULL),
  ('Squirtle', 1, true, NULL, 'Draft Board', 194, '', NULL),
  ('Starly', 1, true, NULL, 'Draft Board', 195, '', NULL),
  ('Stunky', 1, true, NULL, 'Draft Board', 196, '', NULL),
  ('Sunkern', 1, true, NULL, 'Draft Board', 197, '', NULL),
  ('Surskit', 1, true, NULL, 'Draft Board', 198, '', NULL),
  ('Swablu', 1, true, NULL, 'Draft Board', 199, '', NULL),
  ('Swinub', 1, true, NULL, 'Draft Board', 200, '', NULL)
ON CONFLICT (sheet_name, pokemon_name, point_value) DO UPDATE
SET 
  -- Only update pokemon_id if it doesn't violate foreign key constraint
  pokemon_id = CASE 
    WHEN EXCLUDED.pokemon_id IS NULL THEN EXCLUDED.pokemon_id
    WHEN EXISTS (SELECT 1 FROM pokemon_cache WHERE pokemon_id = EXCLUDED.pokemon_id) THEN EXCLUDED.pokemon_id
    ELSE sheets_draft_pool.pokemon_id  -- Keep existing value if new one violates FK
  END,
  sheet_row = EXCLUDED.sheet_row,
  sheet_column = EXCLUDED.sheet_column,
  is_available = EXCLUDED.is_available;
