-- ============================================================================
-- Poképedia Queue-Based Sync System
-- Implements queue-driven ingestion with canonical JSONB cache + normalized tables
-- Based on ChatGPT architecture recommendation
-- ============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS pgmq;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- CANONICAL RESOURCE CACHE (JSONB Store)
-- Stores complete PokéAPI responses for any endpoint
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.pokeapi_resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Resource identification
  resource_type TEXT NOT NULL,          -- e.g. 'pokemon', 'move', 'ability'
  resource_key TEXT NOT NULL,           -- e.g. '25' or 'pikachu' (prefer numeric id)
  name TEXT,                            -- when present
  url TEXT NOT NULL,
  
  -- Payload + caching metadata
  data JSONB NOT NULL,
  etag TEXT,
  last_modified TEXT,
  fetched_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Schema versioning for future migrations
  schema_version INTEGER NOT NULL DEFAULT 1,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Unique constraint on resource_type + resource_key
CREATE UNIQUE INDEX IF NOT EXISTS pokeapi_resources_unique
  ON public.pokeapi_resources(resource_type, resource_key);

-- Index for name lookups
CREATE INDEX IF NOT EXISTS pokeapi_resources_type_name_idx
  ON public.pokeapi_resources(resource_type, name);

-- GIN index for JSONB queries
CREATE INDEX IF NOT EXISTS pokeapi_resources_data_gin
  ON public.pokeapi_resources USING GIN (data jsonb_path_ops);

-- Index for URL lookups
CREATE INDEX IF NOT EXISTS pokeapi_resources_url_idx
  ON public.pokeapi_resources(url);

-- ============================================================================
-- PROJECTION TABLE: Fast Pokédex List/Search
-- Optimized for UI queries (Pokémon listing, search)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.pokepedia_pokemon (
  id INTEGER PRIMARY KEY,                    -- National Dex ID
  name TEXT NOT NULL,
  species_name TEXT,
  height INTEGER,                            -- in decimeters
  weight INTEGER,                            -- in hectograms
  base_experience INTEGER,
  is_default BOOLEAN,
  
  -- Sprite paths (Storage paths, not external URLs)
  sprite_front_default_path TEXT,
  sprite_official_artwork_path TEXT,
  
  -- Timestamps
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for name searches
CREATE INDEX IF NOT EXISTS pokepedia_pokemon_name_idx
  ON public.pokepedia_pokemon(name);

-- Index for species lookups
CREATE INDEX IF NOT EXISTS pokepedia_pokemon_species_name_idx
  ON public.pokepedia_pokemon(species_name);

-- ============================================================================
-- ASSET TABLE: Sprite Metadata
-- Tracks sprites stored in Supabase Storage
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.pokepedia_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Asset classification
  asset_kind TEXT NOT NULL,               -- 'sprite'
  resource_type TEXT,                     -- 'pokemon'
  resource_id INTEGER,                    -- pokemon id when known
  
  -- Source and destination
  source_url TEXT NOT NULL,               -- original sprite URL from PokéAPI
  bucket TEXT NOT NULL,                   -- 'pokedex-sprites'
  path TEXT NOT NULL,                     -- storage object path
  
  -- File metadata
  content_type TEXT,
  bytes INTEGER,
  sha256 TEXT,
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Unique constraint on source URL (prevent duplicate downloads)
CREATE UNIQUE INDEX IF NOT EXISTS pokepedia_assets_source_unique
  ON public.pokepedia_assets(source_url);

-- Unique constraint on bucket + path (prevent path collisions)
CREATE UNIQUE INDEX IF NOT EXISTS pokepedia_assets_bucket_path_unique
  ON public.pokepedia_assets(bucket, path);

-- Index for resource lookups
CREATE INDEX IF NOT EXISTS pokepedia_assets_resource_idx
  ON public.pokepedia_assets(resource_type, resource_id);

-- ============================================================================
-- SUPABASE QUEUES (pgmq)
-- Durable background processing queues
-- ============================================================================

-- Queue for resource ingestion (PokéAPI URLs)
SELECT pgmq.create('pokepedia_ingest');

-- Queue for sprite downloads
SELECT pgmq.create('pokepedia_sprites');

-- ============================================================================
-- HELPER FUNCTIONS
-- ============================================================================

-- Function to get queue depth (for monitoring)
CREATE OR REPLACE FUNCTION public.get_pokepedia_queue_stats()
RETURNS TABLE (
  queue_name TEXT,
  queue_length BIGINT,
  oldest_message_age INTERVAL
) AS $$
DECLARE
  ingest_metrics RECORD;
  sprite_metrics RECORD;
BEGIN
  -- Get metrics for pokepedia_ingest queue
  SELECT 
    (pgmq.metrics('pokepedia_ingest')).queue_length,
    (pgmq.metrics('pokepedia_ingest')).oldest_msg_age
  INTO ingest_metrics;
  
  -- Get metrics for pokepedia_sprites queue
  SELECT 
    (pgmq.metrics('pokepedia_sprites')).queue_length,
    (pgmq.metrics('pokepedia_sprites')).oldest_msg_age
  INTO sprite_metrics;
  
  -- Return results
  RETURN QUERY
  SELECT 
    'pokepedia_ingest'::TEXT AS queue_name,
    COALESCE(ingest_metrics.queue_length, 0)::BIGINT AS queue_length,
    ingest_metrics.oldest_msg_age
  UNION ALL
  SELECT 
    'pokepedia_sprites'::TEXT AS queue_name,
    COALESCE(sprite_metrics.queue_length, 0)::BIGINT AS queue_length,
    sprite_metrics.oldest_msg_age;
END;
$$ LANGUAGE plpgsql;

-- Function to get sync progress (resources synced vs total)
CREATE OR REPLACE FUNCTION public.get_pokepedia_sync_progress()
RETURNS TABLE (
  resource_type TEXT,
  synced_count BIGINT,
  total_estimated BIGINT,
  progress_percent NUMERIC
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    pr.resource_type,
    COUNT(*)::BIGINT AS synced_count,
    CASE 
      WHEN pr.resource_type = 'pokemon' THEN 1025
      WHEN pr.resource_type = 'pokemon-species' THEN 1025
      WHEN pr.resource_type = 'move' THEN 1000
      WHEN pr.resource_type = 'ability' THEN 400
      WHEN pr.resource_type = 'type' THEN 20
      WHEN pr.resource_type = 'item' THEN 2000
      ELSE 100
    END AS total_estimated,
    ROUND(
      (COUNT(*)::NUMERIC / 
       CASE 
         WHEN pr.resource_type = 'pokemon' THEN 1025
         WHEN pr.resource_type = 'pokemon-species' THEN 1025
         WHEN pr.resource_type = 'move' THEN 1000
         WHEN pr.resource_type = 'ability' THEN 400
         WHEN pr.resource_type = 'type' THEN 20
         WHEN pr.resource_type = 'item' THEN 2000
         ELSE 100
       END) * 100, 
      2
    ) AS progress_percent
  FROM public.pokeapi_resources pr
  GROUP BY pr.resource_type
  ORDER BY pr.resource_type;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- STORAGE BUCKET SETUP
-- Note: Bucket creation must be done via Supabase Dashboard or Storage API
-- This migration assumes bucket 'pokedex-sprites' exists
-- ============================================================================

-- RLS Policies (if needed for public access)
ALTER TABLE public.pokeapi_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pokepedia_pokemon ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pokepedia_assets ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public read access to pokeapi_resources
CREATE POLICY "Allow public read access to pokeapi_resources"
  ON public.pokeapi_resources
  FOR SELECT
  USING (true);

-- Policy: Allow public read access to pokepedia_pokemon
CREATE POLICY "Allow public read access to pokepedia_pokemon"
  ON public.pokepedia_pokemon
  FOR SELECT
  USING (true);

-- Policy: Allow public read access to pokepedia_assets
CREATE POLICY "Allow public read access to pokepedia_assets"
  ON public.pokepedia_assets
  FOR SELECT
  USING (true);

-- Policy: Service role can write (for edge functions)
CREATE POLICY "Service role can write pokeapi_resources"
  ON public.pokeapi_resources
  FOR ALL
  USING (auth.role() = 'service_role');

CREATE POLICY "Service role can write pokepedia_pokemon"
  ON public.pokepedia_pokemon
  FOR ALL
  USING (auth.role() = 'service_role');

CREATE POLICY "Service role can write pokepedia_assets"
  ON public.pokepedia_assets
  FOR ALL
  USING (auth.role() = 'service_role');

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON TABLE public.pokeapi_resources IS 'Canonical JSONB cache for all PokéAPI resources. Stores complete API responses for any endpoint.';
COMMENT ON TABLE public.pokepedia_pokemon IS 'Fast projection table for Pokédex listing/search. Optimized for UI queries.';
COMMENT ON TABLE public.pokepedia_assets IS 'Metadata for sprites stored in Supabase Storage. Tracks downloaded assets.';
COMMENT ON FUNCTION public.get_pokepedia_queue_stats() IS 'Returns queue depth and age metrics for monitoring.';
COMMENT ON FUNCTION public.get_pokepedia_sync_progress() IS 'Returns sync progress by resource type (synced vs estimated total).';
